server:
  port: 18080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: novel-editor-ai
  mvc:
    pathmatch:
      use-trailing-slash-match: true
      matching-strategy: ant_path_matcher
  config:
    import: nacos:application-value.yml
  profiles:
    active: value,formal,private
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 100.81.212.120
      config:
        server-addr: 100.81.212.120
        file-extension: yml
        username: nacos
        password: nacos
        namespace: 12705118-223c-456b-817f-3838f5735680
  main:
    allow-circular-references: true
#  ai:
#    vectorstore:
#      chroma:
#        initialize-schema: true
#        collection-name:

#        client:
#          host:
#          port:

#  ai:
#    openai:
#      embedding:
#        base-url: 1
#        api-key: 1
#        options:
#          model: 111
#        embeddings-path: 11
logging:
  level:
    com.soukon.novelEditorAi.mapper: debug
    com.soukon.novelEditorAi: debug