server:
  port: 18080

spring:
  application:
    name: novel-editor-ai
  mvc:
    pathmatch:
      use-trailing-slash-match: true
      matching-strategy: ant_path_matcher
  config:
    import: nacos:application-value.yml
  profiles:
    active: value,formal,private
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 100.81.212.120
      config:
        server-addr: 100.81.212.120
        file-extension: yml
        username: nacos
        password: nacos
        namespace: 12705118-223c-456b-817f-3838f5735680
  main:
    allow-circular-references: true
logging:
  level:
    com.soukon.novelEditorAi.mapper: debug